// COMPREHENDO.md Generator [35]: what the file SAYS, and how two of them differ.
//
// Split from `generate-comprehendo-md.ts` at the project's size gate, the same
// way `corpus-format.ts`/`corpus-source.ts` and `twin.ts`/`twin-validate.ts`
// split before it: everything here is pure and synchronous (bytes in, bytes
// out), and everything there touches a disk, a module loader or an argv.
//
// EVERYTHING RENDERED IS DERIVED. Two kinds of text go in: values read out of
// the packed corpus (Corpus Format [28]'s `pack`) and out of Docs Engine [13]'s
// real topic index, and frozen protocol skeletons quoted from the RFC (the
// completeness contract, RFC 5.5; the priming pointer, RFC 4.1 and 5.5). No
// sentence ABOUT THE PACKAGE is authored here: a claim this generator could
// make that the corpus does not carry is exactly the hand-rotted documentation
// Principle 10 exists to prevent, and the suite holds it to that by rendering
// a differently-identified corpus and finding no word of the first one left.
//
// @see .mdd/docs/35-comprehendo-md-generator.md

import type { PackedCorpus, PackedTopic } from '../packages/registry-tools/dist/corpus-format.js';

/** The generated file's name, at the package root, always this spelling. */
export const OUTPUT_FILE = 'COMPREHENDO.md';

/** How many, spelled with its noun, so "1 topic" never reads as "1 topics". */
export const count = (many: number, noun: string, plural = `${noun}s`): string =>
  `${String(many)} ${many === 1 ? noun : plural}`;

/**
 * Greedy wrap, so a generated paragraph diffs by the line that changed rather
 * than by the whole paragraph. Deterministic: the same text always wraps to
 * the same bytes, which is what makes a byte-for-byte drift gate possible.
 */
function wrap(text: string, width = 76): readonly string[] {
  const lines: string[] = [];
  let current = '';
  for (const word of text.split(/\s+/).filter((piece) => piece !== '')) {
    if (current === '') {
      current = word;
      continue;
    }
    if (current.length + 1 + word.length > width) {
      lines.push(current);
      current = word;
      continue;
    }
    current = `${current} ${word}`;
  }
  if (current !== '') lines.push(current);
  return lines;
}

/** One markdown table cell: single-lined, and never able to break the row. */
const cell = (text: string): string => text.replaceAll(/\s+/g, ' ').replaceAll('|', '\\|').trim();

/**
 * The topic's own opening sentence, which is the answer it gives, shortened to
 * the menu form. Never new prose: this is a slice of the corpus's own summary,
 * so a topic whose answer changes changes this row too.
 */
function openingSentence(summary: string): string {
  const flat = summary.replaceAll(/\s+/g, ' ').trim();
  const end = /[.!?](\s|$)/.exec(flat);
  return end === null ? flat : flat.slice(0, end.index + 1);
}

/**
 * RFC 5.5's completeness contract, verbatim but for the em dash this project
 * does not use. Frozen: an agent that reads a weakened version of this
 * sentence reads the source anyway, which is the whole failure it prevents.
 */
const COMPLETENESS_CONTRACT: readonly string[] = Object.freeze([
  'If it is not documented here it does not exist; do not read the source,',
  'except where an UNDOCUMENTED response permits it for a specific question.',
  'When in doubt, ask `docs()`.',
]);

const GENERATED_NOTICE: readonly string[] = Object.freeze([
  '<!-- Generated from the packed corpus by scripts/generate-comprehendo-md.ts.',
  '     Do not edit this file: an edit here is drift, and CI fails on it. -->',
]);

/** What the corpus says about itself, as one sentence of pure fact. */
function identityParagraph(packed: PackedCorpus, topics: number): string {
  const fixes = packed.twins.entries.reduce((total, entry) => total + entry.fixes.length, 0);
  return [
    `\`${packed.package}\` speaks Comprehendo ${packed.comprehendo}.`,
    `Everything below is generated from \`${packed.provider}\`, a corpus authored`,
    `against ${packed.package} ${packed.version}, which documents`,
    `${count(topics, 'topic')}, ${count(fixes, 'fix', 'fixes')} and`,
    `${count(packed.twins.entries.length, 'cataloged failure')} over the`,
    `\`${packed.twins.declaredSchema.surface}\` call surface`,
    `(${count(packed.twins.declaredSchema.operations.length, 'declared operation')}).`,
  ].join(' ');
}

/**
 * Where an agent gets primed. The priming snippet itself belongs to the entry
 * the marker carries (RFC 5.5), not to this file, so this points at it rather
 * than copying it: a copy is one more thing that can rot behind the corpus.
 *
 * The marker word is read off core's own frozen constant and never re-spelled
 * here (CC9 [10]: one source-of-truth literal, imported everywhere else). Both
 * ecosystems are named because the packed artifact declares no ecosystem, and
 * both spellings are the same word by the same frozen contract.
 */
function primingParagraph(packed: PackedCorpus, marker: string): string {
  return [
    `Probe any value \`${packed.package}\` hands you, a caught error included, for`,
    `\`Symbol.for('${marker}')\` in JavaScript or \`__${marker}__\` in Python.`,
    'The entry that answers carries `identity`, `priming` (the snippet that',
    'primes an agent in roughly a hundred tokens, and is the whole onboarding),',
    'and `docs(query?)`, which answers in the vocabulary you asked in. Nothing',
    'is transmitted anywhere.',
  ].join(' ');
}

/**
 * The fence info-string every rendered example carries.
 *
 * The corpus's own topic files fence with no info-string at all, and this adds
 * one. It is a RENDERING convention, the same class as the table pipes and the
 * cell escaping above, and it makes no claim about the package: what it gives
 * is a real source for the `language` a reader (Docs As Tests [37]) has to
 * dispatch on, instead of an assumption about what an unlabelled fence means.
 *
 * `sh` is the spelling, and the transcript is never handed to a shell: [37]
 * tokenizes it and spawns an argv array, so an operand can never become a
 * command (the same argument corpora/ffmpeg/README.md makes about `apply`).
 */
export const EXAMPLE_LANGUAGE = 'sh';

/**
 * What a block IS, frozen, so a reader is never guessing at the `#` lines.
 *
 * Deliberately says nothing about the package: it describes the shape of the
 * quoted material, which is this renderer's own business, exactly as the
 * generated notice above is.
 */
const EXAMPLES_PREAMBLE: readonly string[] = Object.freeze([
  "These are the corpus's own worked examples, quoted from the topic each one",
  'belongs to. A line beginning with `#` is commentary the corpus carries',
  'beside the command above it, never a command to run.',
]);

/**
 * One worked example, quoted. The heading names the topic it came from and
 * then the example's own title, both read off the corpus; the body is the
 * example's `code` byte for byte, because a quoted example that is not
 * verbatim is a second authoring of it.
 */
function exampleBlock(topic: string, title: string, code: string): readonly string[] {
  return ['', `### \`${topic}\`: ${title}`, '', `\`\`\`${EXAMPLE_LANGUAGE}`, code, '```'];
}

/**
 * Every worked example the corpus carries, in menu order, or nothing at all.
 *
 * A corpus with no examples renders no section rather than an empty heading:
 * a heading over nothing is a promise the corpus did not make, and [37] would
 * then have a surface with zero blocks, which is the honest report for it.
 */
function examplesSection(
  packed: PackedCorpus,
  index: readonly string[],
): readonly string[] {
  const blocks = index.flatMap((name) =>
    (packed.docs.topics[name]?.examples ?? []).flatMap((example) =>
      exampleBlock(name, example.title, example.code),
    ),
  );
  if (blocks.length === 0) return [];
  return ['', '## Examples', '', ...EXAMPLES_PREAMBLE, ...blocks];
}

/** The menu sentence: what `docs()` with no argument really returns. */
const indexParagraph = (topics: number): string =>
  [
    `\`docs()\` with no argument returns exactly these ${count(topics, 'name')}, in this`,
    'order. Ask for one by name, or in any vocabulary it serves; a question no',
    'topic answers comes back UNDOCUMENTED, never as a guess.',
  ].join(' ');

/** One row of the menu, every cell of it read out of the corpus. */
function topicRow(name: string, topic: PackedTopic | undefined): string {
  const summary = topic === undefined ? '' : openingSentence(topic.summary);
  const related = (topic?.see_also ?? []).map((other) => `\`${other}\``).join(', ');
  return `| \`${cell(name)}\` | ${cell(summary)} | ${cell(related)} |`;
}

/**
 * The whole file, from the packed corpus and the index Docs Engine [13]
 * really returned for it. Pure and synchronous: the same inputs are the same
 * bytes, on any machine, in any order, which is what the drift gate compares.
 */
export function renderPacked(
  packed: PackedCorpus,
  index: readonly string[],
  marker: string,
): string {
  const lines: string[] = [
    `# ${packed.package}`,
    '',
    ...GENERATED_NOTICE,
    '',
    ...wrap(identityParagraph(packed, index.length)),
    '',
    ...COMPLETENESS_CONTRACT,
    '',
    '## Priming',
    '',
    ...wrap(primingParagraph(packed, marker)),
    '',
    '## Topics',
    '',
    ...wrap(indexParagraph(index.length)),
    '',
    '| Topic | Answers | See also |',
    '|---|---|---|',
    ...index.map((name) => topicRow(name, packed.docs.topics[name])),
    ...examplesSection(packed, index),
  ];
  return `${lines.join('\n')}\n`;
}

/** Lines present in `from` more times than in `to`, as a multiset difference. */
function surplus(from: readonly string[], to: readonly string[]): readonly string[] {
  const remaining = new Map<string, number>();
  for (const line of to) remaining.set(line, (remaining.get(line) ?? 0) + 1);
  const only: string[] = [];
  for (const line of from) {
    const left = remaining.get(line) ?? 0;
    if (left > 0) {
      remaining.set(line, left - 1);
      continue;
    }
    if (line.trim() !== '') only.push(line);
  }
  return only;
}

/** How many surplus lines one side's report lists before counting the rest off. */
const LISTED = 8;

/** The surplus lines of one side, listed and then counted off. */
function listed(label: string, lines: readonly string[]): readonly string[] {
  if (lines.length === 0) return [];
  const shown = lines.slice(0, LISTED).map((line) => `    ${line}`);
  const rest = lines.length - shown.length;
  return [
    `  ${label} (${count(lines.length, 'line')}):`,
    ...shown,
    ...(rest === 0 ? [] : [`    ... and ${count(rest, 'more line')}`]),
  ];
}

/**
 * What differs, named. Empty means byte-identical.
 *
 * Both halves are reported on purpose: the first differing line locates an
 * edit, and the surplus lists locate an insertion or a deletion, which a
 * positional comparison alone would report as every line after it changing.
 */
export function driftReport(committed: string, regenerated: string): readonly string[] {
  if (committed === regenerated) return [];
  const was = committed.split('\n');
  const now = regenerated.split('\n');
  const at = was.findIndex((line, position) => line !== now[position]);
  const first = at === -1 ? Math.min(was.length, now.length) : at;
  return [
    `  first difference at line ${String(first + 1)}:`,
    `    committed:    ${JSON.stringify(was[first] ?? '(end of file)')}`,
    `    regenerated:  ${JSON.stringify(now[first] ?? '(end of file)')}`,
    ...listed('only in the committed file', surplus(was, now)),
    ...listed('only in the regenerated file', surplus(now, was)),
  ];
}
